# Site settings
title: abuelwafa
email: abuelwafa@abuelwafa.net
description: Mohamed Ali Abuelwafa is a web developer with many years of experience in various web technologies with thorough experience in Javascript, Node.js, Frontend web development and Web Applications.
baseurl: ""
url: "http://abuelwafa.net/"
markdown: kramdown
exclude: ["node_modules", "package.json", "Gruntfile.js", "server-config.json", "README.md", "TODO.md"]
sass:
    style: compressed
